poll_interval: 1s
stable_duration: 1m
retry_interval: 10m
max_parallel_uploads: 5
extensions:
  - .mkv
  - .mp4
  - .m2ts
  - .ts
rclone_args:
  - --drive-chunk-size=256M
  - --checkers=5
  - --transfers=5
  - --drive-stop-on-upload-limit
  - --stats=1s
  - --stats-one-line
  - -v
jobs:
  - name: 4k-remux-sgnb
    source_dir: /dld/upload/4K.REMUX.SGNB
    link_dir: /dld/gd_upload/4K.REMUX.SGNB
    rclone_remote: gd1:/sync/Movie/4K.REMUX.SGNB
